openapi: 3.0.0

info:
  title: 題シェア（仮）
  description: 題シェア（仮） API Server
  version: 0.0.0

servers:
  - url: http://localhost:8000/v1/
    description: A local API server for development

paths:
  /hello:
    get:
      summary: Returns "Hello world."
      responses:
        '200':
          description: Returns "Hello world."
          content:
            text/plain:
              schema:
                type: string
                example: Hello world.