openapi: 3.0.0

info:
  title: 題シェア（仮）
  description: 題シェア（仮） API Server
  version: 0.0.1

servers:
  - url: http://localhost:8000/v1/
    description: A local API server for development


components:
  schemas:
    Idea:
      type: object
      properties:
        text:
          type: string

paths:
  /ideas:
    get:
      summary: Returns ideas
      responses:
        '200':
          description: Returns ideas
          content:
            application/json:
              schema:
                type: object
                properties:
                  ideas:
                    type: array
                    items:
                      $ref: '#/components/schemas/Idea'