openapi: 3.0.0
info:
  description: 題シェア（仮） API Server
  title: 題シェア（仮）
  version: 0.0.1
servers:
- description: A local API server for development
  url: http://localhost:8000/v1/
paths:
  /themes:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200'
          description: Returns themes
      summary: Returns themes
components:
  schemas:
    theme:
      example:
        text: text
      properties:
        text:
          type: string
      type: object
    inline_response_200:
      example:
        themes:
        - text: text
        - text: text
      properties:
        themes:
          items:
            $ref: '#/components/schemas/theme'
          type: array
      type: object
