@startuml wireframe
skinparam DefaultFontName IPAexGothic
(*) --> "{{
  salt
  {
    {+ {!
      題シェア（仮） | 新着お題 | お題ランキング | お題検索 | ログイン
    } }

    {
      {
        { 新着お題 }

        {
          ・～～～～～～～～～～
          ・～～～～～～～～～～
          ・～～～～～～～～～～
          >>もっと見る
        }
      } | {
        {+
          { お題を探す・出す }
          {
            "AAAがBBBしている"
            [ 検索・出題 ]
          }
        }
      }

      {
        { お題ランキング }

        {
          1. ～～～～～～～～～～ | 1,234回答
          { [ 画 ] | [ 画 ] | [ 絵 ] } | *
          { [ 絵 ] | [ 画 ] | [ 絵 ] } | *

          2. ～～～～～～～～～～ | 567回答
          { [ 画 ] | [ 画 ] | [ 絵 ] } | *

          3. ～～～～～～～～～～ | 89回答
          { [ 画 ] | [ 画 ] | [ 絵 ] } | *

          >>もっと見る | *
        }
      } | {
        { 最近回答のあったお題 }

        {
          ～～～～～～～～～～
          { [ 画 ] | [ 画 ] | [ 絵 ] }
          ～～～～～～～～～～
          { [ 画 ] | [ 画 ] | [ 絵 ] }
          ～～～～～～～～～～
          { [ 画 ] | [ 画 ] | [ 絵 ] }

          >>もっと見る
        }
      }
    }

    (c) nahcnuj.
  }
}}" as index

index --> "{{
  salt
  {
    { ログイン }

    { [Twitter] | [Pixiv] | [ニコニコ静画] | … }
  }
}}" as login
login --> "各サービス認証画面" as authenticator
authenticator --> index

index --> "{{
  salt
  {
    { お題検索 }

    { "AAAがBBBしている          " | [検索] }

    { 「<b>AAA</b>が<b>BBB</b>している」の検索結果 }
    
    {
      ～～～～～～～～～～ | *
      { [ 画 ] | [ 画 ] } | *
      {} | >>もっと見る

      ～～～～～～～～～～ | *
      { [ 画 ] | [ 画 ] | [ 絵 ] | [ 絵 ] | [ 絵 ] } | *
      {} | >>もっと見る

      ～～～～～～～～～～ | *
      { [ 画 ] | [ 画 ] | [ 絵 ] } | *
      {} | >>もっと見る

      ︙（自動読み込み）
    }
  }
}}" as search_ideas

index --> "{{
  salt
  {
    { 新着お題 }

    {
      ・～～～～～～～～～～
      ・～～～～～～～～～～
      ・～～～～～～～～～～
      ︙（自動読み込み）
    }
  }
}}" as recent_ideas

index -right-> "{{
  salt
  {
    { お題ランキング }

    {/ <b>累計</b> | 時間 | 日間 | 週間 | 月間 }
    {
      1. ～～～～～～～～～～ | 1,234回答
      { [ 画 ] | [ 画 ] | [ 絵 ] | [ 絵 ] | [ 絵 ] } | *
      {} | >>もっと見る

      2. ～～～～～～～～～～ | 567回答
      { [ 画 ] | [ 画 ] | [ 絵 ] | [ 絵 ] | [ 絵 ] } | *
      {} | >>もっと見る

      3. ～～～～～～～～～～ | 89回答
      { [ 画 ] | [ 画 ] | [ 絵 ] | [ 絵 ] | [ 絵 ] } | *
      {} | >>もっと見る

      ︙（10件）
    }

    { 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 }
  }
}}" as idea_ranking

index --> "{{
  salt
  {
    { 最近回答のあったお題 }
    
    {
      ～～～～～～～～～～ | *
      { [ 画 ] | [ 画 ] } | *
      {} | >>もっと見る

      ～～～～～～～～～～ | *
      { [ 画 ] | [ 画 ] | [ 絵 ] | [ 絵 ] | [ 絵 ] } | *
      {} | >>もっと見る

      ～～～～～～～～～～ | *
      { [ 画 ] | [ 画 ] | [ 絵 ] } | *
      {} | >>もっと見る

      ︙（自動読み込み）
    }
  }
}}" as recent_responded_ideas

recent_ideas --> "{{
  salt
  {
    {
      ～～～～～～～～～（お題）
    }

    {
      [ このお題に回答する ]
    }

    {
      [ 回答イラストを見る ]

      {
        [ 画像 ] | [ 画像 ] | [ 画像 ]
        ○○さん | ○○さん | ○○さん
      }

      {
        [ 画像 ] | [ 画像 ] | [ 画像 ]
        ○○さん | ○○さん | ○○さん
      }

      ︙（自動読み込み）
    }
  }
}}" as idea_detail
idea_ranking --> idea_detail
recent_responded_ideas --> idea_detail
index --> idea_detail
search_ideas --> idea_detail

idea_detail -right-> "イラスト投稿サイト"

idea_detail --> "{{
  salt
  {
    {
      お題「～～～～～～～～～」に回答する
    }

    {
      { 回答イラストを登録する }

      { "https://example.com/illust/xxxxxx" | [確認] }

      { [ サムネ ] }

      { [ 回答 ] }
    }
  }
}}" as respond
respond --> authenticator
authenticator --> respond

@enduml
