// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ThemesColumns holds the columns for the "themes" table.
	ThemesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
	}
	// ThemesTable holds the schema information for the "themes" table.
	ThemesTable = &schema.Table{
		Name:       "themes",
		Columns:    ThemesColumns,
		PrimaryKey: []*schema.Column{ThemesColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ThemesTable,
	}
)

func init() {
}
