// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"log"

	"github.com/nahcnuj/studious-invention/ent/migrate"

	"github.com/nahcnuj/studious-invention/ent/idea"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Idea is the client for interacting with the Idea builders.
	Idea *IdeaClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	cfg := config{log: log.Println, hooks: &hooks{}}
	cfg.options(opts...)
	client := &Client{config: cfg}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Idea = NewIdeaClient(c.config)
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("ent: cannot start a transaction within a transaction")
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:    ctx,
		config: cfg,
		Idea:   NewIdeaClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		config: cfg,
		Idea:   NewIdeaClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Idea.
//		Query().
//		Count(ctx)
//
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.Idea.Use(hooks...)
}

// IdeaClient is a client for the Idea schema.
type IdeaClient struct {
	config
}

// NewIdeaClient returns a client for the Idea from the given config.
func NewIdeaClient(c config) *IdeaClient {
	return &IdeaClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `idea.Hooks(f(g(h())))`.
func (c *IdeaClient) Use(hooks ...Hook) {
	c.hooks.Idea = append(c.hooks.Idea, hooks...)
}

// Create returns a create builder for Idea.
func (c *IdeaClient) Create() *IdeaCreate {
	mutation := newIdeaMutation(c.config, OpCreate)
	return &IdeaCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Idea entities.
func (c *IdeaClient) CreateBulk(builders ...*IdeaCreate) *IdeaCreateBulk {
	return &IdeaCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Idea.
func (c *IdeaClient) Update() *IdeaUpdate {
	mutation := newIdeaMutation(c.config, OpUpdate)
	return &IdeaUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *IdeaClient) UpdateOne(i *Idea) *IdeaUpdateOne {
	mutation := newIdeaMutation(c.config, OpUpdateOne, withIdea(i))
	return &IdeaUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *IdeaClient) UpdateOneID(id int) *IdeaUpdateOne {
	mutation := newIdeaMutation(c.config, OpUpdateOne, withIdeaID(id))
	return &IdeaUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Idea.
func (c *IdeaClient) Delete() *IdeaDelete {
	mutation := newIdeaMutation(c.config, OpDelete)
	return &IdeaDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a delete builder for the given entity.
func (c *IdeaClient) DeleteOne(i *Idea) *IdeaDeleteOne {
	return c.DeleteOneID(i.ID)
}

// DeleteOneID returns a delete builder for the given id.
func (c *IdeaClient) DeleteOneID(id int) *IdeaDeleteOne {
	builder := c.Delete().Where(idea.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &IdeaDeleteOne{builder}
}

// Query returns a query builder for Idea.
func (c *IdeaClient) Query() *IdeaQuery {
	return &IdeaQuery{
		config: c.config,
	}
}

// Get returns a Idea entity by its id.
func (c *IdeaClient) Get(ctx context.Context, id int) (*Idea, error) {
	return c.Query().Where(idea.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *IdeaClient) GetX(ctx context.Context, id int) *Idea {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *IdeaClient) Hooks() []Hook {
	return c.hooks.Idea
}
