// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent/dialect/sql"
	"github.com/nahcnuj/studious-invention/ent/idea"
)

// Idea is the model entity for the Idea schema.
type Idea struct {
	config
	// ID of the ent.
	ID int `json:"id,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Idea) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case idea.FieldID:
			values[i] = new(sql.NullInt64)
		default:
			return nil, fmt.Errorf("unexpected column %q for type Idea", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Idea fields.
func (i *Idea) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for j := range columns {
		switch columns[j] {
		case idea.FieldID:
			value, ok := values[j].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			i.ID = int(value.Int64)
		}
	}
	return nil
}

// Update returns a builder for updating this Idea.
// Note that you need to call Idea.Unwrap() before calling this method if this Idea
// was returned from a transaction, and the transaction was committed or rolled back.
func (i *Idea) Update() *IdeaUpdateOne {
	return (&IdeaClient{config: i.config}).UpdateOne(i)
}

// Unwrap unwraps the Idea entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (i *Idea) Unwrap() *Idea {
	tx, ok := i.config.driver.(*txDriver)
	if !ok {
		panic("ent: Idea is not a transactional entity")
	}
	i.config.driver = tx.drv
	return i
}

// String implements the fmt.Stringer.
func (i *Idea) String() string {
	var builder strings.Builder
	builder.WriteString("Idea(")
	builder.WriteString(fmt.Sprintf("id=%v", i.ID))
	builder.WriteByte(')')
	return builder.String()
}

// Ideas is a parsable slice of Idea.
type Ideas []*Idea

func (i Ideas) config(cfg config) {
	for _i := range i {
		i[_i].config = cfg
	}
}
