/*
 * 題シェア（仮）
 *
 * 題シェア（仮） API Server
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Theme struct {
	Text string `json:"text,omitempty"`
}

// AssertThemeRequired checks if the required fields are not zero-ed
func AssertThemeRequired(obj Theme) error {
	return nil
}

// AssertRecurseThemeRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of Theme (e.g. [][]Theme), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseThemeRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aTheme, ok := obj.(Theme)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertThemeRequired(aTheme)
	})
}
