/*
 * 題シェア（仮）
 *
 * 題シェア（仮） API Server
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Idea struct {
	Text string `json:"text,omitempty"`
}

// AssertIdeaRequired checks if the required fields are not zero-ed
func AssertIdeaRequired(obj Idea) error {
	return nil
}

// AssertRecurseIdeaRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of Idea (e.g. [][]Idea), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseIdeaRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aIdea, ok := obj.(Idea)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertIdeaRequired(aIdea)
	})
}
